[package]
name = "section-8-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
linfa = "0.7"
linfa-clustering = "0.7"
ndarray = "0.15"
csv = "1.3"
serde = { version = "1.0", features = ["derive"] }
plotters = "0.3"